### ISSUE TITLE
Should MAP really be "Mean Interpolated Average Precision"?

### ISSUE THREAD

**Issue by hoonkai** [omni-us/squeezedet-keras#2]
Hi

I should first say that this is a great project! I was just reading through a section of the source for evaluation and noticed the notion of "MAP", which typically means "Mean Average Precision", is implemented as mean of interpolated average precision:

```python
                prmap_feed_dict[mAP_placeholder] = np.mean(AP[:,1], axis=0)

                #save model with biggest mean average precision
                if np.mean(AP[:,1], axis=0) > best_mAP:
                    best_mAP = np.mean(AP[:,1], axis=0)
                    best_mAP_ckpt = current_model
```
https://github.com/omni-us/squeezedet-keras/blob/master/scripts/eval.py#L378-L383

This implementation of MAP returns a larger value than the traditional, of course. Can I ask why the mean of inAP is used here?

Thanks

**Comment by Sileadim** [comment]
Hi
Thank you. The official [Pascal VOC paper](http://homepages.inf.ed.ac.uk/ckiw/postscript/ijcv_voc09.pdf) refers in section 4 to the interpolated version as Average Precision. The subject is a little confusing, as sometimes it is called differently and I have seen different versions. If your implementation produces others results, this might also be due to different interpolation points ( or a bug on my side).

**Comment by hoonkai** [comment]
I'm just trying to reproduce the results of the SqueezeDet paper https://arxiv.org/abs/1612.01051 The mAP reported was in the high 70s, but I've only managed low 60s. The mAP used in the Caffe implementation seems to be arithmetic mean of uninterpolated precision.

**Comment by hoonkai** [comment]
@nischalhp  Sure.
```
BATCH_SIZE = 8
LEARNING_RATE  = 0.01
WEIGHT_DECAY = 0.00002
EPOCHS = 100
```

I've also tried the default LEARNING_RATE and WEIGHT_DECAY values. The loss clearly plateaus well before 100 epochs.
