### ISSUE TITLE
Deployment on server / mobile

### ISSUE THREAD

**Issue by amanmeetgarg** [omni-us/squeezedet-keras#4]
I am trying to deploy the model trained from the repo and custom data to mobile and server side. I am getting strange errors. 

@Sileadim was the model in your use case deployed in mobile and or server side for applications ?

any pointers would be helpful.

Thanks
Aman

**Comment by Sileadim** [comment]
Yes. We deployed it as flask service that returns xml files containing the boxes coordinates. For this you need to extract the preprocessing from the data generator (which we wanted to do in the future) and load the checkpoint file. Since we had this in a separate repository and no time to clean it up it's not in there.  Check out this tutorial for something like this: https://blog.keras.io/building-a-simple-keras-deep-learning-rest-api.html

**Comment by amanmeetgarg** [comment]
@Sileadim  thanks for the sharing the information.  I am trying to convert the model for deployment to coreML for apple. 

at keras function load_model 

keras_model_2 = '/home/ubuntu/squeezedet-keras/experiments/kitti_temp/log/checkpoints/model.99-4.89.hdf5'
model = load_model(keras_model_2)


I keep getting an error for the Lambda Layer. 

    fn = module_objects.get(function_name)
AttributeError: 'NoneType' object has no attribute 'get'

for the Lambda layer : pred_padded = Lambda(self._pad)( pred_reshaped).  in the squeezeDet.py

This is more a Keras question, is there a way to not load a specific Lambda layer OR Did you use any specific api call to be able to load the saved model.

Appreciate your help.

Best
Aman

**Comment by Sileadim** [comment]
Hey. 2 things: 1. You can look here https://github.com/keras-team/keras/issues/4871. 2. You can try to remove the lambda layer. Ususally I just created a new model from the config and loaded the weights. I ran into the same issues when trying to save to a YAML file. Since I started developing with an earlier Keras version, I needed the padding, but it seems that you can just remove this layer in 2.1.2. It seemed to work fine without, but I have not tested it. Just remove it from the file, load you trained model with the custom loading and save it again.

**Comment by nischalhp** [comment]
@amanmeetgarg - Closing this issue now. Please open another one in case you still have queries.

**Comment by egglue** [comment]
@Sileadim Hi You said "You can try to remove the lambda layer. " Does that mean the output layer can just be `pred_reshaped` instead?

Do you know why padding isn't needed?
